# @package habitat.dataset

defaults:
  - /habitat/dataset: dataset_config_schema
  - _self_

type: PointNav-v1
split: val
data_path: data/datasets/pointnav/gibson/v1_only_one_ep_per_scene/{split}/{split}.json.gz