# @package _global_

defaults:
  - /pointnav: ddppo_pointnav
  - /habitat/simulator: dynamic_nav_sim_config_base
  - /habitat/logging: wandb
  # - /habitat/action: gaussian_actions
  - override /habitat/task: dynamicnav
  - override /benchmark/nav/pointnav: pointnav_gibson
  # - override /benchmark/nav/pointnav: pointnav_hm3d
  - override /habitat/simulator/agents@habitat.simulator.agents.main_agent: depth_agent
  - _self_

habitat:
  simulator:
    agents:
      main_agent:
        sim_sensors:
          depth_sensor:
            width: 256
            height: 256

habitat_baselines:
  trainer_name: ver
  eval:
    video_option: ["disk"]