# @package _global_

defaults:
  - pointnav: ddppo_pointnav.yaml
  - override benchmark/nav/pointnav: pointnav_gibson
  # - override benchmark/nav/pointnav: pointnav_hm3d
  # - override benchmark/nav/pointnav: pointnav_mp3d
  - _self_

habitat_baselines:
  num_environments: 1
  trainer_name: ver
  test_episode_count: 4
  eval:
    video_option: ["disk"]
    should_load_ckpt: False
  rl:
    policy:
      name: "PointNavResNetPolicy"
    ppo:
      input_type: depth
    ddppo:
      # pretrained_weights: hz_dynamic_nav/data/saved_weights/gibson-depth-best.pth
      pretrained_weights: hz_dynamic_nav/data/saved_weights/gibson-2plus-resnet50.pth
      # Initialize with pretrained weights
      pretrained: True
      # Initialize just the visual encoder backbone with pretrained weights
      pretrained_encoder: True
      # Whether the visual encoder backbone will be trained.
      train_encoder: True
      # Whether to reset the critic linear layer
      reset_critic: True