# @package _global_

defaults:
  - /pointnav: ddppo_pointnav
  - /habitat/simulator: dynamic_nav_sim_config_base
  - override /habitat/task: dynamicnav

habitat_baselines:
  rl:
    policy:
      action_distribution_type: "gaussian"